"use client";

import Link from "next/link";
import {
  ArrowLeft,
  FileText,
  BookOpen,
  UserCheck,
  UserPlus,
  ShieldCheck,
  UploadCloud,
  Sparkles,
  Ban,
  CreditCard,
  Activity,
  Lock,
  Globe,
  XCircle,
  AlertCircle,
  Shield,
  RefreshCw,
  Gavel,
  Mail,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-linear-to-b from-slate-50 via-white to-slate-50 py-6 sm:py-8 md:py-12 px-3 sm:px-4 md:px-6 lg:px-8 font-sans">
      <div className="max-w-7xl mx-auto space-y-4 sm:space-y-6 md:space-y-8">
        {/* Navigation */}
        <div className="animate-in fade-in slide-in-from-top-4 duration-700">
          <Link href="/">
            <Button
              variant="ghost"
              className="gap-2 pl-0 hover:bg-transparent hover:text-purple-600 transition-all duration-300 text-sm sm:text-base group"
            >
              <ArrowLeft className="w-4 h-4 transition-transform group-hover:-translate-x-1" />
              <span className="hidden xs:inline">Return to Dashboard</span>
              <span className="xs:hidden">Back</span>
            </Button>
          </Link>
        </div>

        {/* Terms Header */}
        <Card className="border-slate-200 duration-500 bg-white overflow-hidden animate-in fade-in slide-in-from-bottom-8 pt-0 pb-6">
          <CardHeader className="pb-6 sm:pb-8 border-b border-slate-100 bg-linear-to-br from-purple-50 via-white to-indigo-50 px-4 sm:px-6 lg:px-8 pt-6 sm:pt-8">
            <div className="flex flex-col sm:flex-row items-start gap-3 sm:gap-4">
              <div className="p-2.5 sm:p-3 bg-linear-to-br from-purple-100 to-purple-200 rounded-xl shadow-md hover:shadow-lg transition-shadow duration-300">
                <FileText className="w-6 h-6 sm:w-8 sm:h-8 text-purple-600" />
              </div>
              <div className="space-y-2 flex-1 w-full">
                <CardTitle className="text-xl sm:text-2xl md:text-3xl font-bold bg-linear-to-r from-purple-600 to-indigo-600 bg-clip-text text-transparent leading-tight">
                  Terms of Service
                  <span className="block text-base sm:text-lg md:text-xl mt-1 font-medium bg-clip-text text-transparent bg-linear-to-r from-slate-600 to-slate-500">
                    Cipher & Row
                  </span>
                </CardTitle>
                <p className="text-xs sm:text-sm text-slate-500 flex items-center gap-1.5 sm:gap-2 flex-wrap">
                  <FileText className="w-3.5 h-3.5 sm:w-4 sm:h-4 shrink-0" />
                  <span>Last Updated: </span>
                  <span className="font-medium">January 2025</span>
                </p>
              </div>
            </div>
            <p className="mt-4 sm:mt-6 text-sm sm:text-base text-slate-600 leading-relaxed">
              Welcome to Cipher & Row. By creating an account, accessing the
              dashboard, using the widget, or installing our code snippet, you
              agree to these Terms of Service (“Terms”). If you do not agree,
              you may not use the Service.
            </p>
          </CardHeader>

          <CardContent className="pt-6 sm:pt-8 px-4 sm:px-6 lg:px-8 space-y-6 sm:space-y-8">
            {/* Definitions */}
            <section className="space-y-3 sm:space-y-4">
              <div className="flex items-center gap-2.5 sm:gap-3 pb-2">
                <div className="p-1.5 sm:p-2 bg-slate-100 rounded-lg shadow-sm hover:shadow-md transition-shadow duration-300">
                  <BookOpen className="w-4 h-4 sm:w-5 sm:h-5 text-slate-600" />
                </div>
                <h2 className="text-lg sm:text-xl font-semibold text-slate-800">
                  Definitions
                </h2>
              </div>
              <ul className="list-disc list-inside text-xs sm:text-sm text-slate-600 space-y-2 ml-2">
                <li>
                  <strong>“Company,” “we,” “us,” “Cipher & Row”</strong> refers
                  to Cipherandrow LLC.
                </li>
                <li>
                  <strong>“Service”</strong> refers to our AI support platform,
                  including the dashboard, widget, APIs, documentation, website,
                  and any related tools.
                </li>
                <li>
                  <strong>“User,” “you,” “Customer”</strong> refers to the
                  individual or entity creating an account and/or using the
                  Service.
                </li>
                <li>
                  <strong>“Account”</strong> means your workspace, client ID,
                  bot ID, settings, and configuration.
                </li>
                <li>
                  <strong>“AI Output”</strong> means any response generated by
                  our AI systems or third-party models.
                </li>
                <li>
                  <strong>“Customer Content”</strong> means KB articles, text,
                  questions, answers, or other materials you upload or input
                  into the Service.
                </li>
              </ul>
            </section>

            <Separator className="my-6 sm:my-8" />

            {/* Eligibility */}
            <section className="space-y-3 sm:space-y-4">
              <div className="flex items-center gap-2.5 sm:gap-3 pb-2">
                <div className="p-1.5 sm:p-2 bg-blue-100 rounded-lg shadow-sm hover:shadow-md transition-shadow duration-300">
                  <UserCheck className="w-4 h-4 sm:w-5 sm:h-5 text-blue-600" />
                </div>
                <h2 className="text-lg sm:text-xl font-semibold text-slate-800">
                  Eligibility
                </h2>
              </div>
              <p className="text-sm text-slate-600">You must:</p>
              <ul className="list-disc list-inside text-xs sm:text-sm text-slate-600 space-y-1.5 ml-2">
                <li>Be at least 18 years old.</li>
                <li>
                  Have authority to enter into a binding agreement on behalf of
                  your organization.
                </li>
                <li>
                  Not be located in a jurisdiction prohibited by U.S. law.
                </li>
              </ul>
            </section>

            <Separator className="my-6 sm:my-8" />

            {/* Account Registration */}
            <section className="space-y-3 sm:space-y-4">
              <div className="flex items-center gap-2.5 sm:gap-3 pb-2">
                <div className="p-1.5 sm:p-2 bg-green-100 rounded-lg shadow-sm hover:shadow-md transition-shadow duration-300">
                  <UserPlus className="w-4 h-4 sm:w-5 sm:h-5 text-green-600" />
                </div>
                <h2 className="text-lg sm:text-xl font-semibold text-slate-800">
                  Account Registration
                </h2>
              </div>
              <p className="text-sm text-slate-600">
                To create an account, you must provide accurate information
                including:
              </p>
              <ul className="list-disc list-inside text-xs sm:text-sm text-slate-600 space-y-1.5 ml-2">
                <li>Your name</li>
                <li>Email address</li>
                <li>Company name (optional)</li>
                <li>Website URL (optional)</li>
              </ul>
              <p className="text-sm text-slate-600 mt-2">
                You are responsible for:
              </p>
              <ul className="list-disc list-inside text-xs sm:text-sm text-slate-600 space-y-1.5 ml-2">
                <li>Maintaining the security of your login credentials</li>
                <li>All activity occurring under your Account</li>
                <li>
                  Ensuring your employees or contractors follow these Terms
                </li>
              </ul>
              <p className="text-sm text-slate-600 mt-2">
                We may refuse registration or suspend accounts for any reason.
              </p>
            </section>

            <Separator className="my-6 sm:my-8" />

            {/* License & Acceptable Use */}
            <section className="space-y-3 sm:space-y-4">
              <div className="flex items-center gap-2.5 sm:gap-3 pb-2">
                <div className="p-1.5 sm:p-2 bg-yellow-100 rounded-lg shadow-sm hover:shadow-md transition-shadow duration-300">
                  <ShieldCheck className="w-4 h-4 sm:w-5 sm:h-5 text-yellow-600" />
                </div>
                <h2 className="text-lg sm:text-xl font-semibold text-slate-800">
                  License & Acceptable Use
                </h2>
              </div>
              <p className="text-sm text-slate-600">
                Cipher & Row grants you a non-exclusive, non-transferable,
                revocable license to use the Service strictly as intended. You
                agree NOT to:
              </p>
              <ul className="list-disc list-inside text-xs sm:text-sm text-slate-600 space-y-1.5 ml-2">
                <li>
                  Use the Service for unlawful, harmful, fraudulent, or abusive
                  purposes
                </li>
                <li>
                  Attempt to access source code, bypass security, or reverse
                  engineer any part of the system
                </li>
                <li>
                  Use the Service to process regulated data (HIPAA, PCI,
                  financial records, children’s data)
                </li>
                <li>
                  Send spam or unauthorized marketing messages through our
                  platform
                </li>
                <li>
                  Misrepresent the Service as your own proprietary technology
                </li>
                <li>
                  Interfere with performance of the Service or other users
                </li>
              </ul>
              <p className="text-sm text-slate-600 mt-2">
                We may suspend or terminate accounts violating this section.
              </p>
            </section>

            <Separator className="my-6 sm:my-8" />

            {/* Customer Content */}
            <section className="space-y-3 sm:space-y-4">
              <div className="flex items-center gap-2.5 sm:gap-3 pb-2">
                <div className="p-1.5 sm:p-2 bg-indigo-100 rounded-lg shadow-sm hover:shadow-md transition-shadow duration-300">
                  <UploadCloud className="w-4 h-4 sm:w-5 sm:h-5 text-indigo-600" />
                </div>
                <h2 className="text-lg sm:text-xl font-semibold text-slate-800">
                  Customer Content
                </h2>
              </div>
              <p className="text-sm text-slate-600">
                You retain ownership of all Customer Content you upload. By
                using the Service, you grant Cipher & Row a limited license to:
              </p>
              <ul className="list-disc list-inside text-xs sm:text-sm text-slate-600 space-y-1.5 ml-2">
                <li>Store Customer Content</li>
                <li>Process it to generate AI Output</li>
                <li>Use it to operate, improve, and maintain the Service</li>
                <li>Display it within your dashboard</li>
              </ul>
              <p className="text-sm text-slate-600 mt-2">
                You represent and warrant that:
              </p>
              <ul className="list-disc list-inside text-xs sm:text-sm text-slate-600 space-y-1.5 ml-2">
                <li>
                  You have the necessary rights to upload Customer Content
                </li>
                <li>Your Content does not infringe any third-party rights</li>
                <li>Your Content complies with all applicable laws</li>
              </ul>
            </section>

            <Separator className="my-6 sm:my-8" />

            {/* AI Output & Reliability */}
            <section className="space-y-3 sm:space-y-4">
              <div className="flex items-center gap-2.5 sm:gap-3 pb-2">
                <div className="p-1.5 sm:p-2 bg-pink-100 rounded-lg shadow-sm hover:shadow-md transition-shadow duration-300">
                  <Sparkles className="w-4 h-4 sm:w-5 sm:h-5 text-pink-600" />
                </div>
                <h2 className="text-lg sm:text-xl font-semibold text-slate-800">
                  AI Output & Reliability
                </h2>
              </div>
              <p className="text-sm text-slate-600">
                The Service uses AI models to generate responses. You
                acknowledge and agree that:
              </p>
              <ul className="list-disc list-inside text-xs sm:text-sm text-slate-600 space-y-1.5 ml-2">
                <li>
                  AI Output may contain inaccuracies, errors, or unexpected
                  language
                </li>
                <li>
                  You are solely responsible for reviewing, approving, and using
                  AI Output
                </li>
                <li>
                  Cipher & Row makes no guarantees regarding reliability or
                  correctness of AI Output
                </li>
                <li>
                  You will not rely solely on AI for sensitive or regulated
                  customer communication
                </li>
              </ul>
              <p className="text-sm text-slate-600 mt-2">
                Cipher & Row is not liable for any harm caused by use or misuse
                of AI Output.
              </p>
            </section>

            <Separator className="my-6 sm:my-8" />

            {/* Prohibited Data Types */}
            <section className="space-y-3 sm:space-y-4">
              <div className="flex items-center gap-2.5 sm:gap-3 pb-2">
                <div className="p-1.5 sm:p-2 bg-red-100 rounded-lg shadow-sm hover:shadow-md transition-shadow duration-300">
                  <Ban className="w-4 h-4 sm:w-5 sm:h-5 text-red-600" />
                </div>
                <h2 className="text-lg sm:text-xl font-semibold text-slate-800">
                  Prohibited Data Types
                </h2>
              </div>
              <p className="text-sm text-slate-600">
                You agree NOT to upload or process:
              </p>
              <ul className="list-disc list-inside text-xs sm:text-sm text-slate-600 space-y-1.5 ml-2">
                <li>Credit card numbers</li>
                <li>Bank account info</li>
                <li>Social Security numbers</li>
                <li>
                  Medical information or protected health information (PHI)
                </li>
                <li>Financial account credentials</li>
                <li>Government-issued ID numbers</li>
                <li>Legal complaints or regulated filings</li>
                <li>Highly sensitive personal data of any kind</li>
              </ul>
              <p className="text-sm text-slate-600 mt-2">
                Cipher & Row is not designed to handle regulated data
                categories.
              </p>
            </section>

            <Separator className="my-6 sm:my-8" />

            {/* Billing & Payment */}
            <section className="space-y-3 sm:space-y-4">
              <div className="flex items-center gap-2.5 sm:gap-3 pb-2">
                <div className="p-1.5 sm:p-2 bg-emerald-100 rounded-lg shadow-sm hover:shadow-md transition-shadow duration-300">
                  <CreditCard className="w-4 h-4 sm:w-5 sm:h-5 text-emerald-600" />
                </div>
                <h2 className="text-lg sm:text-xl font-semibold text-slate-800">
                  Billing & Payment Terms
                </h2>
              </div>
              <p className="text-sm text-slate-600">
                Paid plans are billed via Stripe. By subscribing, you authorize:
              </p>
              <ul className="list-disc list-inside text-xs sm:text-sm text-slate-600 space-y-1.5 ml-2">
                <li>Recurring monthly or annual charges</li>
                <li>Charges for usage exceeding plan limits</li>
                <li>Stripe to store your payment method</li>
              </ul>
              <p className="text-sm text-slate-600 mt-2">
                All fees are non-refundable, except when required by law.
              </p>
              <p className="text-xs sm:text-sm text-slate-600 font-medium mt-2 bg-emerald-50 p-2.5 sm:p-3 rounded-lg border border-emerald-100">
                Trials convert automatically to paid plans unless canceled
                before the trial ends. We may update pricing at any time with
                notice.
              </p>
            </section>

            <Separator className="my-6 sm:my-8" />

            {/* Availability & Security */}
            <div className="grid md:grid-cols-2 gap-8">
              <section className="space-y-3 sm:space-y-4">
                <div className="flex items-center gap-2.5 sm:gap-3 pb-2">
                  <div className="p-1.5 sm:p-2 bg-orange-100 rounded-lg shadow-sm hover:shadow-md transition-shadow duration-300">
                    <Activity className="w-4 h-4 sm:w-5 sm:h-5 text-orange-600" />
                  </div>
                  <h2 className="text-lg sm:text-xl font-semibold text-slate-800">
                    Service Availability
                  </h2>
                </div>
                <p className="text-sm text-slate-600">
                  We strive for uptime but do not guarantee:
                </p>
                <ul className="list-disc list-inside text-xs sm:text-sm text-slate-600 space-y-1.5 ml-2">
                  <li>Uninterrupted service</li>
                  <li>Error-free operation</li>
                  <li>Specific response times</li>
                </ul>
                <p className="text-sm text-slate-600 mt-2">
                  We may modify, suspend, or discontinue any part of the Service
                  without liability.
                </p>
              </section>

              <section className="space-y-3 sm:space-y-4">
                <div className="flex items-center gap-2.5 sm:gap-3 pb-2">
                  <div className="p-1.5 sm:p-2 bg-sky-100 rounded-lg shadow-sm hover:shadow-md transition-shadow duration-300">
                    <Lock className="w-4 h-4 sm:w-5 sm:h-5 text-sky-600" />
                  </div>
                  <h2 className="text-lg sm:text-xl font-semibold text-slate-800">
                    Data Security & Privacy
                  </h2>
                </div>
                <p className="text-sm text-slate-600">
                  Cipher & Row uses reasonable security measures. However:
                </p>
                <ul className="list-disc list-inside text-xs sm:text-sm text-slate-600 space-y-1.5 ml-2">
                  <li>No system is 100% secure</li>
                  <li>You use the Service at your own risk</li>
                  <li>
                    We are not responsible for unauthorized access caused by you
                    or third parties
                  </li>
                </ul>
                <p className="text-sm text-slate-600 mt-2">
                  See our Privacy Policy for full details.
                </p>
              </section>
            </div>

            <Separator className="my-6 sm:my-8" />

            {/* Third Party & Termination */}
            <div className="grid md:grid-cols-2 gap-8">
              <section className="space-y-3 sm:space-y-4">
                <div className="flex items-center gap-2.5 sm:gap-3 pb-2">
                  <div className="p-1.5 sm:p-2 bg-gray-100 rounded-lg shadow-sm hover:shadow-md transition-shadow duration-300">
                    <Globe className="w-4 h-4 sm:w-5 sm:h-5 text-gray-600" />
                  </div>
                  <h2 className="text-lg sm:text-xl font-semibold text-slate-800">
                    Third-Party Services
                  </h2>
                </div>
                <p className="text-sm text-slate-600">
                  The Service may include integrations with third parties (e.g.,
                  Stripe, Supabase, LLM providers). You acknowledge:
                </p>
                <ul className="list-disc list-inside text-xs sm:text-sm text-slate-600 space-y-1.5 ml-2">
                  <li>We do not control these third-party services</li>
                  <li>They may have outages or limitations</li>
                  <li>Your use of them is governed by their terms</li>
                </ul>
                <p className="text-sm text-slate-600 mt-2">
                  We are not liable for third-party failures.
                </p>
              </section>

              <section className="space-y-3 sm:space-y-4">
                <div className="flex items-center gap-2.5 sm:gap-3 pb-2">
                  <div className="p-1.5 sm:p-2 bg-rose-100 rounded-lg shadow-sm hover:shadow-md transition-shadow duration-300">
                    <XCircle className="w-4 h-4 sm:w-5 sm:h-5 text-rose-600" />
                  </div>
                  <h2 className="text-lg sm:text-xl font-semibold text-slate-800">
                    Termination
                  </h2>
                </div>
                <p className="text-sm text-slate-600">
                  We may suspend or terminate your Account for:
                </p>
                <ul className="list-disc list-inside text-xs sm:text-sm text-slate-600 space-y-1.5 ml-2">
                  <li>Violation of these Terms</li>
                  <li>Abuse or excessive load</li>
                  <li>Non-payment</li>
                  <li>Security risks</li>
                </ul>
                <p className="text-sm text-slate-600 mt-2">Upon termination:</p>
                <ul className="list-disc list-inside text-xs sm:text-sm text-slate-600 space-y-1.5 ml-2">
                  <li>Your license ends</li>
                  <li>Access to your dashboard and bot is revoked</li>
                  <li>We may delete your content after a reasonable period</li>
                </ul>
              </section>
            </div>

            <Separator className="my-6 sm:my-8" />

            {/* Disclaimers & Liability */}
            <section className="space-y-3 sm:space-y-4">
              <div className="flex items-center gap-2.5 sm:gap-3 pb-2">
                <div className="p-1.5 sm:p-2 bg-amber-100 rounded-lg shadow-sm hover:shadow-md transition-shadow duration-300">
                  <AlertCircle className="w-4 h-4 sm:w-5 sm:h-5 text-amber-600" />
                </div>
                <h2 className="text-lg sm:text-xl font-semibold text-slate-800">
                  Disclaimers
                </h2>
              </div>
              <p className="text-sm text-slate-600">
                To the fullest extent permitted by law:
              </p>
              <ul className="list-disc list-inside text-xs sm:text-sm text-slate-600 space-y-1.5 ml-2">
                <li>The Service is provided “as-is” and “as available.”</li>
                <li>We disclaim all warranties, express or implied.</li>
                <li>
                  We do not guarantee accuracy, reliability, or completeness of
                  AI Output.
                </li>
              </ul>
            </section>

            <Separator className="my-6 sm:my-8" />

            {/* Limitation of Liability */}
            <section className="space-y-3 sm:space-y-4">
              <div className="flex items-center gap-2.5 sm:gap-3 pb-2">
                <div className="p-1.5 sm:p-2 bg-red-100 rounded-lg shadow-sm hover:shadow-md transition-shadow duration-300">
                  <Ban className="w-4 h-4 sm:w-5 sm:h-5 text-red-600" />
                </div>
                <h2 className="text-lg sm:text-xl font-semibold text-slate-800">
                  Limitation of Liability
                </h2>
              </div>
              <p className="text-sm text-slate-600">
                To the fullest extent allowed by law, Cipher & Row is not liable
                for:
              </p>
              <ul className="list-disc list-inside text-xs sm:text-sm text-slate-600 space-y-1.5 ml-2">
                <li>Loss of profits</li>
                <li>Loss of data</li>
                <li>Business interruption</li>
                <li>Indirect or consequential damages</li>
                <li>Errors or unexpected AI Output</li>
                <li>Outages, delays, or third-party failures</li>
              </ul>
              <p className="text-sm text-slate-600 mt-2">
                Our total liability for any claim will not exceed the amount you
                paid us in the last 3 months.
              </p>
            </section>

            <Separator className="my-6 sm:my-8" />

            {/* Indemnification & Modifications */}
            <div className="grid md:grid-cols-2 gap-8">
              <section className="space-y-3 sm:space-y-4">
                <div className="flex items-center gap-2.5 sm:gap-3 pb-2">
                  <div className="p-1.5 sm:p-2 bg-teal-100 rounded-lg shadow-sm hover:shadow-md transition-shadow duration-300">
                    <Shield className="w-4 h-4 sm:w-5 sm:h-5 text-teal-600" />
                  </div>
                  <h2 className="text-lg sm:text-xl font-semibold text-slate-800">
                    Indemnification
                  </h2>
                </div>
                <p className="text-sm text-slate-600">
                  You agree to indemnify and hold Cipher & Row harmless from any
                  claim arising from:
                </p>
                <ul className="list-disc list-inside text-xs sm:text-sm text-slate-600 space-y-1.5 ml-2">
                  <li>Your use of the Service</li>
                  <li>Your Customer Content</li>
                  <li>Your violation of the Terms</li>
                  <li>Your misuse of AI Output</li>
                </ul>
              </section>

              <section className="space-y-3 sm:space-y-4">
                <div className="flex items-center gap-2.5 sm:gap-3 pb-2">
                  <div className="p-1.5 sm:p-2 bg-cyan-100 rounded-lg shadow-sm hover:shadow-md transition-shadow duration-300">
                    <RefreshCw className="w-4 h-4 sm:w-5 sm:h-5 text-cyan-600" />
                  </div>
                  <h2 className="text-lg sm:text-xl font-semibold text-slate-800">
                    Modifications to Terms
                  </h2>
                </div>
                <p className="text-sm text-slate-600">
                  We may update these Terms at any time. Continued use of the
                  Service means you accept the updated Terms.
                </p>
              </section>
            </div>

            <Separator className="my-6 sm:my-8" />

            {/* Governing Law & Contact */}
            <div className="grid md:grid-cols-2 gap-8">
              <section className="space-y-3 sm:space-y-4">
                <div className="flex items-center gap-2.5 sm:gap-3 pb-2">
                  <div className="p-1.5 sm:p-2 bg-violet-100 rounded-lg shadow-sm hover:shadow-md transition-shadow duration-300">
                    <Gavel className="w-4 h-4 sm:w-5 sm:h-5 text-violet-600" />
                  </div>
                  <h2 className="text-lg sm:text-xl font-semibold text-slate-800">
                    Governing Law
                  </h2>
                </div>
                <p className="text-sm text-slate-600">
                  These Terms are governed by the laws of:
                  <br />
                  <strong>Wyoming, USA</strong>
                  <span className="block text-slate-400 text-xs mt-1">
                    (or wherever your LLC is registered)
                  </span>
                </p>
                <p className="text-sm text-slate-600">
                  Any disputes will be resolved exclusively in that
                  jurisdiction.
                </p>
              </section>

              <section className="space-y-3 sm:space-y-4">
                <div className="flex items-center gap-2.5 sm:gap-3 pb-2">
                  <div className="p-1.5 sm:p-2 bg-blue-100 rounded-lg shadow-sm hover:shadow-md transition-shadow duration-300">
                    <Mail className="w-4 h-4 sm:w-5 sm:h-5 text-blue-600" />
                  </div>
                  <h2 className="text-lg sm:text-xl font-semibold text-slate-800">
                    Contact
                  </h2>
                </div>
                <div className="flex flex-col gap-1">
                  <p className="text-sm text-slate-600">Questions?</p>
                  <p className="text-sm font-semibold text-slate-800">
                    Cipher & Row
                  </p>
                  <a
                    href="mailto:support@cipherandrow.com"
                    className="text-blue-600 hover:text-blue-700 hover:underline inline-flex items-center gap-1.5 font-medium transition-colors duration-300 text-sm"
                  >
                    support@cipherandrow.com
                  </a>
                  <a
                    href="https://www.cipherandrow.com"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-blue-600 hover:text-blue-700 hover:underline inline-flex items-center gap-1.5 font-medium transition-colors duration-300 text-sm"
                  >
                    www.cipherandrow.com
                  </a>
                </div>
              </section>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
